# lightGBM

- Author: Wen Xin
- Description: This file is about using lightGBM to do regression for our problem.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [9]:
data=pd.read_csv('regression_data.csv')

In [10]:
data.head()

order_sd  active_days  lastgap   avg_gap  min_gap  max_gap  \
0  0.663138           10      3.0  4.888889      1.0     12.0   
1  0.602960           18      7.0  2.941176      1.0     11.0   
2  0.391684           13      5.0  4.500000      2.0     12.0   
3  0.337142            9      5.0  8.625000      1.0     53.0   
4  0.535490           12      5.0  3.454545      1.0      6.0   

   w1_total_orders  w2_total_orders  w3_total_orders  w4_total_orders  ...  \
0              4.0              2.0              2.0              6.0  ...   
1              8.0              5.0              3.0              1.0  ...   
2              3.0              2.0              2.0              1.0  ...   
3              2.0              0.0              0.0              0.0  ...   
4              0.0              0.0              0.0              2.0  ...   

   log_send2update_time_max  kitchen_royalty  staple_price  like_num  \
0                 11.227614         1.875000           2.0      11.0   
1                 11.297663         1.833333           1.0       0.0   
2                 11.237844         2.600000           2.0     116.0   
3                 11.244497         2.250000           3.0      40.0   
4                 11.235207         1.363636           2.0       0.0   

   dummy_like_num  dummy_has_kitchen_info  dummy_staple_price  comment_perc  \
0             1.0                       1                   1      0.250000   
1             0.0                       1                   1      0.227273   
2             1.0                       1                   1      0.923077   
3             1.0                       1                   1      0.000000   
4             0.0                       1                   1      0.800000   

     user_id    gap  
0  100002020  100.0  
1  100002033  100.0  
2  100002035  100.0  
3  100002036    1.0  
4  100002040    1.0  

[5 rows x 124 columns]

In [11]:
data.gap.unique()

array([100.,   1.,   2.,   5.,   4.,  15.,   6.,  23.,  22.,  28.,  19.,
         7.,   8.,  30.,  45.,  43.,  27.,  49.,  32.,  16.,  33.,  42.,
         3.,  61.,   9.,  36.,  35.,  50.,  10.,  17.,  74.,  11.,  12.,
        39.,  13.,  48.,  53.,  18.,  14.,  26.,  60.,  20.,  56.,  82.,
        55.,  47.,  24.,  29.,  71.,  46.,  31.,  40.,  51.,  25.,  63.,
        21.,  79.,  58.,  59.,  34.,  83.,  72.,  37.,  65.,  80.,  62.,
        77.,  70.,  57.,  52.,  54.,  38.,  64.,  66.,  41.,  75.,  44.,
        68.,  73.,  67.,  78.,  76.,  69.,  81.])

In [13]:
data_1=data[data.gap!=100]
data_1.head()

order_sd  active_days  lastgap   avg_gap  min_gap  max_gap  \
3  0.337142            9      5.0  8.625000      1.0     53.0   
4  0.535490           12      5.0  3.454545      1.0      6.0   
6  0.957589           24      4.0  2.913043      1.0      7.0   
7  0.905584           16      2.0  3.600000      1.0      8.0   
8  0.884184           38      4.0  1.810811      1.0      6.0   

   w1_total_orders  w2_total_orders  w3_total_orders  w4_total_orders  ...  \
3              2.0              0.0              0.0              0.0  ...   
4              0.0              0.0              0.0              2.0  ...   
6              7.0              8.0              3.0              6.0  ...   
7              0.0              7.0              3.0              3.0  ...   
8              7.0             13.0              6.0              4.0  ...   

   log_send2update_time_max  kitchen_royalty  staple_price  like_num  \
3                 11.244497         2.250000           3.0      40.0   
4                 11.235207         1.363636           2.0       0.0   
6                 11.250040         1.300000          -1.0       0.0   
7                 11.253144         1.500000          -1.0       0.0   
8                 11.261691         2.230769           3.0     173.0   

   dummy_like_num  dummy_has_kitchen_info  dummy_staple_price  comment_perc  \
3             1.0                       1                   1      0.000000   
4             0.0                       1                   1      0.800000   
6             0.0                       0                   0      0.256410   
7             0.0                       0                   0      0.111111   
8             1.0                       1                   1      0.534483   

     user_id  gap  
3  100002036  1.0  
4  100002040  1.0  
6  100002044  2.0  
7  100002050  5.0  
8  100002052  2.0  

[5 rows x 124 columns]

In [15]:
list(data_1.columns)

['order_sd',
 'active_days',
 'lastgap',
 'avg_gap',
 'min_gap',
 'max_gap',
 'w1_total_orders',
 'w2_total_orders',
 'w3_total_orders',
 'w4_total_orders',
 'w5_total_orders',
 'w6_total_orders',
 'w7_total_orders',
 'first_order',
 'last_order',
 'accountLength',
 'overall_time_mean',
 'update2create_time_mean',
 'send2update_time_mean',
 'overall_time_min',
 'update2create_time_min',
 'send2update_time_min',
 'overall_time_max',
 'update2create_time_max',
 'send2update_time_max',
 'intime_rate',
 'last_coupon_fee',
 'last_send_type',
 'order_nums',
 'city_id',
 'sex',
 'age',
 'login_platform_b',
 'app_version_b',
 'age_na',
 'lastgap_na',
 'avg_gap_na',
 'min_gap_na',
 'max_gap_na',
 'overall_time_mean_na',
 'update2create_time_mean_na',
 'send2update_time_mean_na',
 'overall_time_min_na',
 'update2create_time_min_na',
 'send2update_time_min_na',
 'overall_time_max_na',
 'update2create_time_max_na',
 'send2update_time_max_na',
 'w1_avg_couponworth',
 'w2_avg_couponworth',
 'w3_avg_

In [16]:
cols=['order_sd',
 'active_days',
 'lastgap',
 'avg_gap',
 'min_gap',
 'max_gap',
 'w1_total_orders',
 'w2_total_orders',
 'w3_total_orders',
 'w4_total_orders',
 'w5_total_orders',
 'w6_total_orders',
 'w7_total_orders',
 'first_order',
 'last_order',
 'accountLength',
 'overall_time_mean',
 'update2create_time_mean',
 'send2update_time_mean',
 'overall_time_min',
 'update2create_time_min',
 'send2update_time_min',
 'overall_time_max',
 'update2create_time_max',
 'send2update_time_max',
 'intime_rate',
 'last_coupon_fee',
 'last_send_type',
 'order_nums',
 'city_id',
 'sex',
 'age',
 'login_platform_b',
 'app_version_b',
 'age_na',
 'lastgap_na',
 'avg_gap_na',
 'min_gap_na',
 'max_gap_na',
 'overall_time_mean_na',
 'update2create_time_mean_na',
 'send2update_time_mean_na',
 'overall_time_min_na',
 'update2create_time_min_na',
 'send2update_time_min_na',
 'overall_time_max_na',
 'update2create_time_max_na',
 'send2update_time_max_na',
 'w1_avg_couponworth',
 'w2_avg_couponworth',
 'w3_avg_couponworth',
 'w4_avg_couponworth',
 'w5_avg_couponworth',
 'w6_avg_couponworth',
 'w7_avg_couponworth',
 'w1_max_couponworth',
 'w2_max_couponworth',
 'w3_max_couponworth',
 'w4_max_couponworth',
 'w5_max_couponworth',
 'w6_max_couponworth',
 'w7_max_couponworth',
 'log_order_sd',
 'log_active_days',
 'log_total_orders',
 'log_w1_total_orders',
 'log_w2_total_orders',
 'log_w3_total_orders',
 'log_w4_total_orders',
 'log_w5_total_orders',
 'log_w6_total_orders',
 'log_w7_total_orders',
 'log_first_order',
 'log_last_order',
 'log_accountLength',
 'log_overall_time_mean',
 'log_overall_time_min',
 'log_overall_time_max',
 'log_intime_rate',
 'log_last_coupon_fee',
 'log_order_nums',
 'log_w1_avg_couponworth',
 'log_w2_avg_couponworth',
 'log_w3_avg_couponworth',
 'log_w4_avg_couponworth',
 'log_w5_avg_couponworth',
 'log_w6_avg_couponworth',
 'log_w7_avg_couponworth',
 'log_w1_max_couponworth',
 'log_w2_max_couponworth',
 'log_w3_max_couponworth',
 'log_w4_max_couponworth',
 'log_w5_max_couponworth',
 'log_w6_max_couponworth',
 'log_w7_max_couponworth',
 'dummy_log_lastgap',
 'log_lastgap',
 'dummy_log_avg_gap',
 'log_avg_gap',
 'dummy_log_min_gap',
 'log_min_gap',
 'dummy_log_max_gap',
 'log_max_gap',
 'dummy_log_update2create_time_mean',
 'log_update2create_time_mean',
 'dummy_log_send2update_time_mean',
 'log_send2update_time_mean',
 'dummy_log_update2create_time_min',
 'log_update2create_time_min',
 'dummy_log_send2update_time_min',
 'log_send2update_time_min',
 'dummy_log_update2create_time_max',
 'log_update2create_time_max',
 'dummy_log_send2update_time_max',
 'log_send2update_time_max',
 'kitchen_royalty',
 'staple_price',
 'like_num',
 'dummy_like_num',
 'dummy_has_kitchen_info',
 'dummy_staple_price',
 'comment_perc',
 'gap']

In [18]:
data_2=data_1[cols]
data_2.head()

order_sd  active_days  lastgap   avg_gap  min_gap  max_gap  \
3  0.337142            9      5.0  8.625000      1.0     53.0   
4  0.535490           12      5.0  3.454545      1.0      6.0   
6  0.957589           24      4.0  2.913043      1.0      7.0   
7  0.905584           16      2.0  3.600000      1.0      8.0   
8  0.884184           38      4.0  1.810811      1.0      6.0   

   w1_total_orders  w2_total_orders  w3_total_orders  w4_total_orders  ...  \
3              2.0              0.0              0.0              0.0  ...   
4              0.0              0.0              0.0              2.0  ...   
6              7.0              8.0              3.0              6.0  ...   
7              0.0              7.0              3.0              3.0  ...   
8              7.0             13.0              6.0              4.0  ...   

   dummy_log_send2update_time_max  log_send2update_time_max  kitchen_royalty  \
3                             1.0                 11.244497         2.250000   
4                             1.0                 11.235207         1.363636   
6                             1.0                 11.250040         1.300000   
7                             1.0                 11.253144         1.500000   
8                             1.0                 11.261691         2.230769   

   staple_price  like_num  dummy_like_num  dummy_has_kitchen_info  \
3           3.0      40.0             1.0                       1   
4           2.0       0.0             0.0                       1   
6          -1.0       0.0             0.0                       0   
7          -1.0       0.0             0.0                       0   
8           3.0     173.0             1.0                       1   

   dummy_staple_price  comment_perc  gap  
3                   1      0.000000  1.0  
4                   1      0.800000  1.0  
6                   0      0.256410  2.0  
7                   0      0.111111  5.0  
8                   1      0.534483  2.0  

[5 rows x 123 columns]

In [71]:
data_2.to_csv('data.csv',index=False)

In [19]:
X=data_2
y=data_2['gap']
X=X.drop(['gap'],axis=1)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
import lightgbm as lgb

In [23]:
categorical_features=[
 'last_send_type',
 'city_id',
 'sex',
 'age',
 'login_platform_b',
 'app_version_b',
 'age_na',
 'lastgap_na',
 'avg_gap_na',
 'min_gap_na',
 'max_gap_na',
 'overall_time_mean_na',
 'update2create_time_mean_na',
 'send2update_time_mean_na',
 'overall_time_min_na',
 'update2create_time_min_na',
 'send2update_time_min_na',
 'overall_time_max_na',
 'update2create_time_max_na',
 'send2update_time_max_na',
 'dummy_log_lastgap',
 'dummy_log_avg_gap',
 'dummy_log_min_gap',
 'dummy_log_max_gap',
 'dummy_log_update2create_time_mean',
 'dummy_log_send2update_time_mean',
 'dummy_log_update2create_time_min',
 'dummy_log_send2update_time_min',
 'dummy_log_update2create_time_max',
 'dummy_log_send2update_time_max']

In [24]:
# if you want to re-use data, remember to set free_raw_data=False
lgb_train = lgb.Dataset(X_train, y_train,\
                        categorical_feature=categorical_features,free_raw_data=False)
lgb_test = lgb.Dataset(X_test, y_test, reference=lgb_train,
                       categorical_feature=categorical_features, free_raw_data=False)

In [61]:
params = {
    'boosting_type': 'gbdt',
    'num_leaves': 31,
    'max_depth':-1,
    'learning_rate': 0.05,
    'n_estimators':100,
    'objective': 'regression',
    'silent':False,
    'verbose': 0
}

In [62]:
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=10,
                valid_sets=lgb_train)

[1]	training's l2: 200.519
[2]	training's l2: 182.195
[3]	training's l2: 165.657
[4]	training's l2: 150.728
[5]	training's l2: 137.255
[6]	training's l2: 125.092
[7]	training's l2: 114.114
[8]	training's l2: 104.204
[9]	training's l2: 95.2588
[10]	training's l2: 87.1829
[11]	training's l2: 79.894
[12]	training's l2: 73.3132
[13]	training's l2: 67.3717
[14]	training's l2: 62.0062
[15]	training's l2: 57.16
[16]	training's l2: 52.789
[17]	training's l2: 48.8388
[18]	training's l2: 45.2752
[19]	training's l2: 42.0552
[20]	training's l2: 39.1498
[21]	training's l2: 36.5247
[22]	training's l2: 34.1555
[23]	training's l2: 32.0149
[24]	training's l2: 30.0829
[25]	training's l2: 28.3362
[26]	training's l2: 26.7593
[27]	training's l2: 25.3364
[28]	training's l2: 24.0501
[29]	training's l2: 22.8878
[30]	training's l2: 21.8393
[31]	training's l2: 20.8901
[32]	training's l2: 20.0331
[33]	training's l2: 19.2591
[34]	training's l2: 18.56
[35]	training's l2: 17.9275
[36]	training's l2: 17.3559
[37]	tr

In [67]:
train_predict=gbm.predict(X_train)
test_predict=gbm.predict(X_test)

In [68]:
from sklearn.metrics import mean_absolute_error

In [72]:
np.where(train_predict<0,0,train_predict)

array([ 7.24638446, 32.79371866,  4.50553833, ..., 24.9257889 ,
       10.72303392,  4.06902212])

In [79]:
np.where(test_predict<0,0,test_predict)

array([ 1.77838414,  2.855124  , 21.02148957, ..., 67.51124115,
        5.25308572,  4.27834067])

In [77]:
mean_absolute_error(y_train, train_predict)

2.7833463594653653

In [70]:
mean_absolute_error(y_test, test_predict)

2.849977467133864

In [80]:
mean_absolute_error(y_test, np.where(test_predict<0,0,test_predict))

2.849977467133864